version: "3.3"

services:
  postgres:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - chatbot_be
  opa:
    image: openpolicyagent/opa:latest-debug
    restart: always
    ports:
      - "8181:8181"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - run
      - --server
      - --log-level=debug
      - --set=services.api.url=http://host.docker.internal:8000
      - --set=bundles.api.service=api
      - --set=bundles.api.resource=/api/opa/rules
      - --set=bundles.api.polling.min_delay_seconds=5
      - --set=bundles.api.polling.max_delay_seconds=15

networks:
  chatbot_be:
    driver: bridge
